title: Jack Frysinger
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Jack's first real attempt to build a personal website. Bear with him as he develops his tone and discovers interesting things to write about.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jackfrysinger.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jackfrys
github_username:  jackfrys

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
